import { supabase } from './supabaseClient'

// Owner-only (notifications_select/_update RLS, migration 054) - the
// unified activity feed replacing the scattered per-page banners
// (OwnerHome's negative-feedback banner, EstimatesPage's stale-estimate
// banner). Every row is system-generated by a SECURITY DEFINER trigger or
// the flag_stale_estimates() cron job - this file only ever reads and
// marks-read, it never inserts.

const PAGE_SIZE = 40

export async function listNotifications() {
  const { data, error } = await supabase
    .from('notifications')
    .select('*')
    .order('created_at', { ascending: false })
    .limit(PAGE_SIZE)
  if (error) throw error
  return data
}

// Cheap count-only query for the bell badge - avoids pulling full rows
// just to show a number before the notification center is even opened.
export async function getUnreadNotificationCount() {
  const { count, error } = await supabase
    .from('notifications')
    .select('id', { count: 'exact', head: true })
    .is('read_at', null)
  if (error) throw error
  return count || 0
}

export async function markNotificationRead(id) {
  const { error } = await supabase.from('notifications').update({ read_at: new Date().toISOString() }).eq('id', id)
  if (error) throw error
}

export async function markAllNotificationsRead() {
  const { error } = await supabase.from('notifications').update({ read_at: new Date().toISOString() }).is('read_at', null)
  if (error) throw error
}
